const words = {
    "landmark" : "dönüm noktası",
    "canny" : "kurnaz, açıkgöz",
    "merry" : "neşeli",
    "twinkle" : "pırıltı",
    "stupendous" : "muazzam",
    "ought" : "-meli",
    "soundness" : "sağlamlık, doğruluk",
    "revolutionize" : "devrim yapmak",
    "whatsoever" : "ne olursa olsun",
    "astounding" : "şaşırtıcı, hayret verici",
    "conceived" : "tasarlanmış",
    "ridiculing" : "alay konusu",
    "stillborn" : "ölü doğmuş",
    "roughly" : "kabaca",
    "deprive" : "mahrum etmek, yoksun bırakmak",
    "manuscript" : "el yazması",
    "ploughed" : "güçlükle ilerlemek",
    "forged ahead" : "ileriye doğru ilerlemek",
    "vaguely" : "belli belirsiz",
    "surmount" : "aşmak, üstesinden gelmek",
    "handicapped" : "yetersiz",
    "susceptibility" : "duyarlılık",
    "futile" : "nafile, boş",
    "self-pity" : "kendine acımak",
    "envious" : "kıskanç",
    "excel" : "üstün olmak, geçmek",
    "sarcastic" : "alaycı, iğneleyici",
    "immunity" : "bağışıklık, dokunulmazlık",
    "counteracting" : "karşı koyma",
    "provocation" : "kışkırtma",
    "susceptible" : "duyarlı",
    "ambush" : "pusuya düşürmek, pusu",
    "bores" : "sıkıcı, sıkıntı",
    "forfeit" : "ceza",
    "stricken" : "yakalanmış, yaralı",
    "affliction" : "ızdırap, ders",
    "oasis" : "vaha",
    "convinced" : "inanmış",
    "sweep" : "sürüklemek",
    "intentionally" : "kasıtlı olarak",
    "icandescent" : "akkor, göz kamaştırıcı",
    "opposing" : "karşıt",
    "fulfillment" : "yerine getirme",
    "anquaintance" : "tanıdık",
    "possession" : "mülk, sahiplik",
    "abuse" : "suistimal etmek",
    "mobilize" : "harekete geçirmek",
    "prominence" : "şöhret",
    "soften" : "yumuşatmak, zayıflatmak",
    "subdue" : "boyun eğdirmek, bastırmak",
    "linger" : "oyalanmak, can çekişmek",
    "allegedly" : "iddiaya göre",
    "catastrophe" : "felaket, afet",
    "philanthropic" : "hayırsever",
    "corroborate" : "doğrulamak, onaylamak",
    "valve" : "kapak",
    "altitude" : "rakım, yükseklik",
    "unholy" : "dine aykırı, kötücül",
    "crystallize" : "kristalleşmek",
    "germinate" : "filizlendirmek",
    "abode" : "ikametgah, konut",
    "thrive" : "gelişmek, serpilmek",
    "fruitful" : "verimli, bereketli",
    "solely" : "sadece, yalnızca",
    "plainly" : "açıkça",
    "trembling" : "titreyen, titrek",
    "anticipation" : "beklenti",
    "reap" : "biçmek, kazanmak",
    "outwit" : "atlatmak, kurnazlıkla yenmek",
    "industrialist" : "sanayici",
    "cyclone" : "siklon, kasırga",
    "deprivation" : "yoksunluk",
    "parlour" : "salon, oturma odası",
    "determined" : "azimli, kararlı",
    "undertaken" : "üstlenilen",
    "aid" : "yardım",
    "distinguish" : "ayırt etmek, ayrım yapmak",
    "consequence" : "sonuçlar",
    "conclusion" : "çözüm, sonuç, karar",
    "self-determination" : "özgür irade, özerklik",
    "concerned" : "söz konusu olmak",
    "meager" : "yetersiz",
    "epiphany" : "aydınlanma",
    "endeavor" : "çaba",
    "contentment" : "hoşnutluk",
    "fiction" : "kurgu",
    "stimulus" : "uyarıcı",
    "layman" : "sıradan insanlar",
    "possess" : "sahip olmak",
    "acclaimed" : "alkışlanan",
    "prosperity" : "refah, zenginlik",
    "rural" : "kırsal",
    "orphan" : "yetim",
    "brought up" : "büyütülmüş",
    "rebellious" : "asi, isyankar",
    "renowned" : "ünlü",
    "dominate" : "hakim olmak",
    "monumental" : "anıtsal",
    "approach" : "yaklaşmak, yaklaşım",
    "refurbished" : "yenilenmiş",
    "illustration" : "örnekleme",
    "exemplify" : "örnek oluşturmak",
    "promulgate" : "ilan etmek",
    "in addition" : "ek olarak",
    "achiever" : "başarılı kimse",
    "comtemporarie" : "çağdaş",
    "therefore" : "öyleyse",
    "precepts" : "kurallar",
    "harmony" : "uyum",
    "partnership" : "ortaklık",
    "persistence" : "süreklilik, devamlılık",
    "definite" : "kesin, belirli",
    "observe" : "gözlemlemek",
    "impulse" : "dürtü",
    "upon" : "üzerine",
    "rail" : "demiryolu",
    "fare" : "ücret",
    "sufficient" : "yeterli, elverişli",
    "freight" : "naklive",
    "present" : "sunmak, tanıtmak",
    "announce" : "duyurmak",
    "tramp" : "serseri",
    "subsequent" : "sonraki",
    "occasion" : "fırsat",
    "nominal" : "göstermelik, düşük",
    "merchandise" : "mal, eşya",
    "intended" : "amaçlanan",
    "apparently" : "görünüşe göre",
    "coveted" : "imrenilen",
    "intensify" : "yoğunlaştırmak",
    "seek" : "araştırmak, aramak",
    "accomplish" : "başarmak, sonuçlandırmak",
    "adopt" : "benimsemek",
    "sly" : "kurnaz sinsi",
    "intermediary" : "aracı, arabulucu",
    "slipping in" : "içeri girmek",
    "enthusiastic" : "hevesli, istekli",
    "queer-looking" : "tuhaf görünüşlü",
    "crawl" : "sürünmek, emeklemek",
    "promptly" : "derhal, acilen",
    "distribute" : "dağıtmak",
    "alliance" : "birlik, anlaşma",
    "fence" : "çit, parmaklık",
    "intangible" : "soyut, manevi",
    "tangible" : "somut",
    "transmute" : "dönüştürmek",
    "counterpart" : "karşılık",
    "influence" : "etki",
    "initiative" : "girişkenlik",
    "lust" : "arzu",
    "pick and shovel" : "kazma ve kürek",
    "smelter" : "dökümhane",
    "pot" : "tencere, kap",
    "drill" : "delik açmak",
    "desperately" : "umutsuzca",
    "all to no avail" : "hepsi boşuna",
    "irritable" : "asabi, sinirli",
    "nag" : "dırdır etmek",
    "junk" : "hurda",
    "junk man" : "hurdacı",
    "counsel" : "avukat, danışman",
    "procure" : "temin etmek, sağlamak",
    "scowling" : "sert bakan, çatık kaşlı",
    "frowning" : "kaşlarını çatmak, hoşnutsuz",
    "outward" : "dışa doğru, dışarıya",
    "sole" : "tek, biricik",
    "afterward" : "sonrasında",
    "recoup" : "telafi etmek, karşılamak",
    "earnest" : "ciddi, ağırbaşlı",
    "profit" : "yararlanmak, kar etmek",
    "stickability" : "yapışkanlık",
    "quitability" : "vazgeçilebilirlik",
    "overtaken" : "geride bırakmak",
    "trickster" : "düzenbaz",
    "cunning" : "marifetli, kurnaz",
    "keen" : "keskin",
    "discouragement" : "cesaret kırıklığı",
    "procession" : "alay",
    "delight" : "zevk, sevinç",
    "wheat" : "buğday",
    "mill" : "değirmen",
    "sharecrop" : "ortak ürün",
    "meekly" : "uysalca",
    "retorted" : "sert cevap vermek",
    "budge" : "kıpırdamak",
    "temper" : "öfke",
    "fierce" : "şiddetli",
    "shrill" : "tiz",
    "pondering" : "düşünme, kafa yormak",
    "awe" : "korku",
    "whipping" : "kırbaçlama",
    "deliberately" : "kasten",
    "authority" : "yetki",
    "fierciness" : "sertlik",
    "docile" : "uysal",
    "lamb" : "kuzu",
    "superior" : "amir",
    "author" : "yazar",
    "musty" : "küflü",
    "conquest" : "fetih",
    "instruction" : "talimat",
    "stumbled upon" : "tesadüfen bulmak",
    "cerebral hemorrhage" : "beyin kanaması",
    "cultivate" : "yetiştirmek",
    "throughout" : "boyunca",
    "deluged" : "sel basmak ,su baskını",
    "rescue" : "kurtarmak",
    "catch a glimpse" : "göz atmak",
    "littleness" : "küçüklük, önemsizlik",
    "quicken" : "hızlandırmak",
    "irresistible" : "dayanılmaz",
    "unwittingly" : "farkında olmadan",
    "disillusioned" : "hayel aleminden çıkmış",
    "household" : "ev, eve ait",
    "proponent" : "savunucu",
    "frankly" : "açıkçası",
    "acknowledge" : "kabullenmek",
    "inseparably" : "ayrılmaz bir şekilde",
    "minor" : "küçük, ikincil",
    "movie stardom" : "film yıldızı",
    "prospect" : "olasılık",
    "defiance" : "meydan okurcasına",
    "glaring" : "göze batan, apaçık, göz kamaştırıcı",
    "in disguise" : "kılık değiştirmiş",
    "imponderable" : "ölçülemez",
    "inclination" : "eğilim",
    "ponder over" : "üzerine düşünmek",
    "spring into" : "içine girmek",
    "entitled" : "hak sahibi",
    "annoyance" : "sıkıntı, rahatsızlık",
    "abundance" : "bolluk",
    "expediency" : "menfaat, çıkar",
    "astounding" : "şaşırtıcı",
    "take into consideration" : "göz önünde bulundurmak",
    "destruction" : "yıkım",
    "transmuted" : "dönüştürülmüş",
    "gradually" : "gitgide",
    "sphere" : "küre",
    "stake" : "riske atmak",
    "neatly" : "düzgün şekilde",
    "clip it out" : "kesmek",
    "conscious" : "bilinçli",
    "indifferently" : "kayıtsızca, aldırışsızca",
    "steeped" : "kökleşmek",
    "envy" : "imrenmek",
    "reluctant" : "isteksiz",
    "cast" : "döküm",
    "instruct" : "talimat vermek, öğretmek",
    "stroke " : "vuruş",
    "accuracy" : "doğruluk, kesinlik",
    "substance" : "öz, içerik",
    "deduce" : "sonuç çıkarmak",
    "necessity" : "gereklilik",
    "entrance" : "büyülemek, hayran bırakmak",
    "fate" : "kader",
    "conceivable" : "makul, akla uygun",
    "equivalent" : "eş değer",
    "transmute" : "dönüştürmek",
    "influence" : "etkilemek",
    "adopts" : "benimsemek, kabul etmek",
    "prophetic" : "kehanet niteliğinde",
    "foresight" : "öngörü",
    "devote" : "adamak, ayırmak",
    "endeavor" : "çaba harcamak, gayret etmek",
    "philanthropic" : "hayırsever",
    "urge" : "teşvik etmek",
    "subside" : "yatışmak, sakinleşmek",
    "overabundance" : "fazlalık",
    "humility" : "tevazu, alçakgönüllülük",
    "stinging" : "batma, keskin",
    "indictment" : "suçlama",
    "expedient" : "uygun, avantajlı",
    "acknowledge" : "kabullenmek, onaylamak",
    "mediocrity" : "sıradanlık",
    "plaintiff" : "davacı, şikayetçi",
    "break into" : "zorla girmek",
    "motion picture" : "sinema filmi",
    "exemplify" : "örneklemek, örnek oluşturmak",
    "interpret" : "yorumlamak",
    "stating" : "dile getirmek, belirtmek, açıklamak",
    "contented" : "memnun",
    "magnetize" : "çekmek, cezbetmek",
    "harmonize" : "uyumlu hale getirmek",
    "sneaked off" : "gizlice kaçmak",
    "befriending" : "arkadaş olmak, yardım etmek",
    "acclaim" : "beğeni, alkış",
    "desperately" : "umutsuzca",
    "despite" : "aksine , rağmen",
    "diminished" : "azalmış",
    "persuade" : "ikna etmek",
    "dismiss" : "görevden almak",
    "beset" : "rahat vermemek, kuşatmak",
    "critic" : "eleştirmek",
    "comprehensive" : "kapsayıcı",
    "incorporate" : "dahil etmek",
    "prominently" : "belirgin bir şekilde",
    "demonstrate" : "göstermek, kanıtlamak",
    "conduct" : "yönetmek",
    "enhance" : "genişletmek, büyütmek",
    "far-flung" : "uzaklara yayılmış",
    "accredit" : "güvenmek, itibar etmek",
    "heroic" : "kahramanca, destansı",
    "departure" : "kalkış, gidiş",
    "bathe" : "yıkanmak, yüzmek",
    "connotation" : "çağrışım",
    "liberty" : "özgürlük",
    "factual" : "gerçek",
    "enduring" : "dayanıklı",
    "examine" : "incelemek, sorgulamak",
    "mogul" : "patron, kral",
    "merchandise" : "satılık eşya, ticaret yapmak",
    "freight train" : "yük treni",
    "resemble" : "benzemek",
    "tramp" : "serseri",
    "presence" : "varlık, huzur",
    "keen" : "hevesli, istekli",
    "aforethought" : "önceden düşünülmüş",
    "pulsating" : "nabız gibi atan",
    "transcend" : "aşmak, üstün olmak",
    "induce" : "teşvik etmek",
    "attain" : "ulaşmak, elde etmek",
    "indelible" : "silinmez, sabit",
    "remarkable" : "dikkat çekici, dikkate değer",
    "cog" : "çark dişi",
    "ray of hope" : "umut ışığı",
    "attainment" : "ulaşma, kazanma",
    "ephemeral" : "geçici, fani",
    "transitory" : "geçici, süreksiz",
    "imprint" : "damga, etki",
    "resentful" : "kırgın, dargın",
    "communion" : "cemaat, birlik",
    "inanimate" : "cansız, donuk",
    "handiwork" : "el işi, yapıt",
    "obstruction" : "tıkanıklık, engel",
    "commonplace" : "sıradan, olağan",
    "abide" : "katlanmak, beklemek",
    "shed" : "baraka",
    "shed" : "dökmek",
    "thorn" : "diken",
    "edible" : "yenilebilir",
    "splendor" : "ihtişam, görkem",
    "emulation" : "özenme",
    "potter’s clay" : "çömlekçi çamuru",
    "clay" : "çamur, kil",
    "nagging" : "dırdır etmek, başının etini yemek",
    "affinity" : "yakınlık, ilgi",
    "hold out" : "uzatmak, ümit vermek",
    "cherished" : "değerli",
    "menial" : "vasıfsız",
    "content" : "memnun",
    "triumph" : "zafer, başarı",
    "retreat" : "geri çekilmek",
    "whimsical" : "kaprisli, garip",
    "temperamental" : "huysuz, maymun iştahlı",
    "perish" : "yok olmak",
    "deliberation" : "üzerinde düşünme",
    "foe" : "düşman, rakip",
    "shore" : "sahil, kıyı",
    "maintaining" : "sürdürmek, korumak",
    "merchant" : "tüccar",
    "towering" : "yüksek",
    "monument" : "anıt",
    "fellow" : "arkadaş, yoldaş",
    "dismal" : "kasvetli",
    "distinguish" : "ayırt etmek",
    "persistence" : "ısrar, devamlılık",
    "recognize" : "farkına varmak, kabul etmek, tanımak",
    "establish" : "belirlemek, saptamak",
    "acquisition" : "kazanma, edinme",
    "state" : "belirtmek, ifade etmek",
    "accumulate" : "biriktirmek",
    "complying" : "uymak, razı olmak",
    "remedy" : "düzeltmek, tedavi etmek",
    "aid" : "yardım",
    "eagerness" : "heves, sabırsızlık",
    "gravitate" : "yer çekimi, çekilmek",
    "keenly" : "hevelse",
    "conscious" : "bilinçli",
    "consciousness" : "bilinç",
    "saturate" : "doyurmak",
    "thoroughly" : "iyice, tamamen",
    "impractical" : "pratik olmayan, kullanışsız",
    "convey" : "iletmek, taşımak",
    "laborer" : "işçi, amele",
    "despite" : "aksine, rağmen",
    "yield" : "vermek, sağlamak",
    "consider" : "dikkate almak",
    "considerably" : "önemli ölçüde",
    "further" : "daha öte, ayrıca",
    "scrutinize" : "dikkatle incelemek",
    "stamp of approval" : "onay damgası",
    "accumulation" : "birikim",
    "attainment" : "ulaşma",
    "credulous" : "saf, her şeye inanan",
    "dawn" : "şafak",
    "demand" : "talep etmek",
    "intangible" : "soyut, elle tutulmaz",
    "impulse" : "dürtü",
    "convenience" : "kolaylık, elverişlilik",
    "pleasant" : "keyifli",
    "tolerance" : "hata payı",
    "doomed" : "mahkum",
    "pioneer" : "öncü",
    "favorable" : "elverişli",
    "remold" : "yeniden şekillendirmek",
    "scorn" : "aşağılamak",
    "stake" : "riske atmak",
    "denounce" : "kınamak",
    "lest" : "olmaya ki, etmesin diye",
    "emphatically" : "kesinlikle, vurgulayarak",
    "rekindle" : "alevlendirmek, yeniden yakmak",
    "embolden" : "cesaretlendirmek, teşvik etmek",
    "triumph" : "zafer",
    "shrine" : "türbe",
    "worship" : "ibadet etnek",
    "permit" : "izin vermek",
    "alibi" : "mazeret",
    "horseless carriage" : "atsız taşıma aracı",
    "favor" : "iyilik",
    "stately" : "görkemli",
    "fold" : "katlamak, kıvırmak",
    "manor" : "malikane",
    "entertainment" : "eğlence, gösteri",
    "disseminated" : "yayılmış",
    "taken into custody" : "gözaltına alındı",
    "accustomed" : "alışık, alışılmış",
    "indeed" : "aslında",
    "readiness" : "hazırlık",
    "indifference" : "kayıtsızlık, ilgisizlik",
    "scoff" : "alay etmek",
    "confine" : "sınırlamak",
    "sorely" : "şiddetle, fena halde",
    "religious" : "dini",
    "misfortune" : "talihsizlik",
    "confine" : "sınırlamak",
    "vivid" : "parlak, canlı",
    "acquainted" : "haberdar olma",
    "cellular" : "hücresel, hücre",
    "step up" : "yükseltmek, yükselmek",
    "outcast" : "dışlanmış",
    "undergo" : "uğramak, katlanmak",
    "innumerable" : "sayısız",
    "pasting" : "yapıştırma",
    "pots" : "tencere",
    "love affair" : "aşk ilişkisi",
    "transmuting" : "dönüştürme",
    "constructive" : "yapıcı",
    "indelibly" : "silinmez bir şekilde",
    "lad" : "delikanlı",
    "drunkard" : "ayyaş",
    "poetry" : "şiir",
    "thorn" : "diken",
    "plucking" : "koparma",
    "handicapped" : "özürlü, sakat",
    "impress" : "etkilemek",
    "endure" : "dayanmak",
    "governor" : "vali",
    "emigrate" : "göç etmek",
    "sought" : "aranan",
    "opulence" : "zenginlik, bolluk",
    "minor" : "küçük",
    "complacent" : "kayıtsız",
    "censure" : "kınama, eleştri",
    "irreparable" : "onarilamaz, tamir edilemez",
    "chum" : "dostum, arkadaş",
    "ail" : "hasta, hasta olmak",
    "polygamous" : "çok eşli",
    "havoc" : "tahribat, yıkım",
    "infidelity" : "sadakatsizlik, ihanet",
    "germinate" : "çimlenmek, filizlenmek",
    "vengeance" : "intikam",
    "climate" : "iklim, hava",
    "affair" : "mesele, ilişki",
    "gratis" : "bedava, parasız",
    "reputable" : "saygın",
    "inferiority" : "aşağılık, adilik",
    "resentment" : "kızgınlık, içerleme",
    "heredity" : "kalıtım",
    "eschew" : "kaçınmak",
    "overwhelmingly" : "ezici çoğunlukla",
    "elect" : "seçmek, atamak",
    "strive" : "çabalamak",
    "adapt" : "adapte olmak",
    "despondent" : "umutsuz, morali bozuk",
    "dissuade" : "daydırmak",
    "lend" : "ödünç vermek",
    "wholehearted" : "içten, samimi",
    "kindle" : "tutuşmak, alevlendirmek",
    "anew" : "yeniden",
    "proverb" : "atasözü",
    "byword" : "özdeyiş",
    "thee" : "sana",
    "winding" : "dolambaçlı",
    "thy" : "senin",
    "tender" : "hassas",
    "craveth" : "özlem",
    "prosperity" : "refah",
    "misery" : "sefalet",
    "bergain" : "pazarlık",
    "scanty" : "yetersiz",
    "bear" : "üstlenmek",
    "dismayed" : "dehşete düşmüş",
    "attributed" : "bağladı",
    "svelte" : "zarif",
    "crown" : "taç",
    "preach" : "vaaz vermek",
    "firmly" : "sıkıca",
    "excellence" : "mükemmellik",
    "undisturbed" : "rahatsız edilmemiş, rahat",
    "capable" : "kapasiteye sahip, yeterli",
    "incomprehensible" : "anlaşılmaz, akıl almaz",
    "reflect" : "yansıtmak, düşünmek",
    "deviate" : "sapmak, saptırmak",
    "corrective" : "düzeltici",
    "outwit" : "zekası ile alt etmek",
    "stipulate" : "şart koymak",
    "climax" : "doruk, zirve",
    "express" : "ifade etmek, açıklamak",
    "conceive" : "düşünmek",
    "timid" : "ürkek, korkak",
    "caution" : "uyarmak",
    "faze" : "şaşırtmak",
    "demonstrate" : "göstermek",
    "tangible" : "somut, elle tutulur",
    "coup" : "darbe",
    "immense" : "engin, muazzam, uçsuz bucaksız",
    "secrecy" : "gizlilik",
    "induce" : "teşvik etmek",
    "affliction" : "ızdırap, acı",
    "immortal" : "ölümsüz, sonsuz",
    "prompted" : "yönlendirmek",
    "recede" : "geri çekilmek, vazgeçmek",
    "disfigure" : "şeklini bozmak",
    "transplant" : "nakli, nakletmek",
    "sweep" : "süpürmek",
    "desperation" : "çaresizlik",
    "eccentric" : "eksantrik, alışılmadık",
    "extricate" : "kurtarmak",
    "oar" : "kürek",
    "undergo" : "uğramak, başına gelmek",
    "resembling" : "benzeyen",
    "interfere" : "müdahale etmek",
    "confine" : "sınırlamak",
    "woo" : "kur yapmak, elde etmeye çalışmak",
    "pursuit of" : "peşinde",
    "informal" : "resmi olmayan",
    "defect" : "kusur, arıza",
    "endorse" : "onaylamak, desteklemek",
    "contribute" : "katkı yapmak",
    "stream of" : "akışı",
    "cooperate" : "işbirliği yapmak",
    "renewed" : "yenilenmiş",
    "pledge" : "rehin",
    "ecstasies" : "coşku",
    "prior" : "önceki, öncelikli",
    "dissipation" : "dağılma, yayma",
    "channel" : "kanalize etmek",
    "sown" : "ekilmiş",
    "sowing one’s wild oats" : "yabani yulaf ekmek",
    "promptly" : "derhal",
    "appropriate" : "uygun",
    "preference" : "tercih",
    "occasion" : "fırsat",
    "clamped" : "kenetlenmiş",
    "conduction" : "iletim",
    "stabs" : "bıçaklamak",
    "outlook" : "görünüm",
    "plainly" : "açıkça",
    "self-reliance" : "kendine güven",
    "emphasize" : "vurgulamak",
    "confess" : "itiraf etmek",
    "adequate" : "yeterli",
    "wrath" : "gazap, öfke, hiddet",
    "compensation" : "tazminat",
    "retrospect" : "geçmişe bakmak",
    "astounding" : "şaşırtıcı",
    "reflect" : "yansıtmak, düşünmek",
    "extraordinary" : "olağanüstü",
    "ware" : "eşya, mal",
    "industrious" : "çalışkan",
    "gradually" : "gitgide",
    "self-conscious" : "içine kapanık",
    "bear" : "taşımakj",
    "privilege" : "ayrıcalık",
    "consent" : "onay",
    "matter" : "konu, mesele",
    "servant" : "hizmetkar",
    "shin" : "tırmanmak",
    "clenched" : "sıkılmış, sıkmak",
    "heartily" : "yürekten",
    "endeavor" : "çaba",
    "venture" : "girişim",
    "cruellest" : "en zalim, acıması",
    "initiative" : "insiyatif, başlatan",
    "pleased" : "memnun",
    "resourcefullness" : "beceriklilik",
    "alibis" : "mazeretler",
    "permit" : "izin vermek",
    "associate" : "ilişki kurmak",
    "disclosed" : "açıklandı",
    "stroke" : "vuruş",
    "overjoyed" : "aşırı memnun",
    "perform" : "uygulamak, yapmak",
    "converse" : "sohbet etmek",
    "persistent" : "kalıcı, sürekli",
    "induce" : "teşvik etmek, uyarmak",
    "commence" : "başlamak",
    "dividend" : "kar payı",
    "intoxicate" : "sarhoş etmek, kendinden geçirmek",
    "enthusiastically" : "coşkuyla",
    "hunch" : "kambur",
    "substance" : "içerik, esas",
    "preliminary" : "ön hazırlık",
    "bourne" : "memleket, dere",
    "freeing" : "serbest bırakmak",
    "insidious" : "sinsi, hain",
    "molest" : "sarkıntılık yapmak",
    "antagonist" : "rakip, düşman",
    "presumably" : "muhtemelen, herhalde",
    "hither" : "buraya",
    "yon" : "işte, şuradaki",
    "chip" : "yonga, fiş",
    "unremitting" : "aralıksız, sürekli",
    "discontinue" : "son vermek, durdurmak",
    "uncanny" : "esrarengiz, acayip",
    "accustom" : "alıştırmak",
    "swarm" : "sürü, yığın",
    "hive" : "kovan, arı kovanı",
    "disintegrate" : "parçalanmak, dağılmak",
    "rescue" : "kurtarmak, muaf tutmak",
    "chid" : "azarlamak, söylenmek",
    "serpent" : "yılan",
    "folded" : "katlanmış",
    "steadfast" : "sadık, kararlı",
    "adversity" : "sıkıntı, zorluk",
    "astound" : "hayrete düşürmek, şaşırtmak",
    "solemn" : "ağırbaşlı, resmi",
    "drawdown" : "aşağıya çekmek, indirmek",
    "poise" : "denge, duruş",
    "salute" : "selamlamak",
    "groan" : "inlemek, sızlanmak",
    "incite" : "tetiklemek, kışkırtmak",
    "clasp" : "teklemek, tutturmak",
    "witty" : "esprili, nükteli",
    "repartee" : "hazırcevap",
    "pulpit" : "kürsü, iletişim aracı",
    "sunder" : "ayrılmak, kopmak",
    "bias" : "ön yargı, eğilim",
    "devote" : "adamak, ayırmak",
    "intensive" : "yoğun",
    "doomed" : "mahkum",
    "prejudice" : "ön yargı, zarar, sakınca",
    "untiring" : "yorulmak bilmez",
    "indebted" : "teşekkür borçlu, minnettar",
    "relief" : "rahatlama",
    "mutism" : "dilsizlik",
    "conduct" : "yönetmek, idare etmek",
    "sceptical" : "şüpheci, kuşkucu",
    "demonstration" : "gösteri, ispat",
    "enlarge" : "büyütmek",
    "arouse" : "uyandırmak, canlandırmak",
    "examine" : "incelemek",
    "thoroughly" : "iyice, tamamen",
    "astound" : "hayrete düşürmek",
    "whatsoever" : "ne olursa olsun",
    "span" : "aşmak",
    "gulf" : "körfez, uçurum",
    "keen" : "hevesli, istekli",
    "interpret" : "yorumlamak",
    "sacrilege" : "saygısızlık",
    "conjecture" : "varsayım",
    "neglected" : "ihmal etmek, bakımsız",
    "assume" : "farz etmek",
    "devious" : "dolambaçlı",
    "adequate" : "yeterli",
    "compensation" : "tazminat",
    "affliction" : "ızdırap, acı",
    "capitalize" : "sermayeleştirmek",
    "submerge" : "batırmak, daldırmak",
    "outlet" : "çıkış",
    "demonstrate" : "göstermek, kanıtlamak",
    "enthusiasm" : "heves, heyecan",
    "superficial" : "yüzeysel, üstünkörü",
    "enrich" : "zenginleştirmek",
    "dam up" : "baraj yapmak",
    "immovable" : "taşınmaz",
    "key up" : "canlandırmak",
    "castrate" : "hadım etmek",
    "docile" : "uysal",
    "alteration" : "değişiklik",
    "stimuli" : "uyaranlar",
    "inborn" : "doğuştan",
    "providential" : "ilahi",
    "bend" : "boyun eğmek",
    "will" : "irade, niyet, istek",
    "inponderable" : "ölçülemez",
    "counterpart" : "karşılık",
    "modus operandi" : "işleyiş tarzı",
    "bedfellow" : "yatak arkadaşı, karı, dost",
    "broadcasting" : "yayın",
    "quiescent" : "hareketsiz, sakin",
    "astounding" : "şaşırtıcı",
    "conceivable" : "düşünülebilir, makul, akla uygun",
    "emaciated" : "bir deri bir kemik",
    "absent" : "mevcut olmayan, devamsız",
    "physician" : "doktor",
    "harness" : "dizginlemek",
    "convey" : "iletmek",
    "attainment" : "ulaşma, kazanma",
    "spiritual" : "manevi",
    "transmit" : "iletmek, yaymak",
    "induce" : "teşvik etmek",
    "psychic" : "ruhsal, ruhani",
    "affirmation" : "onaylama",
    "instruction" : "talimat, yönerge",
    "presumably" : "muhtemelen",
    "intangible" : "soyut, manevi",
    "counterpart" : "karşılık, eş, benzer",
    "procuring" : "tedarik etme",
    "abhor" : "iğrenmek, nefret etmek",
    "accustomed" : "alışık, alışkın",
    "endure" : "dayanmak, katlanmak",
    "proceed" : "ilerlemek, devam etmek",
    "vitality" : "canlılık, güç",
    "destructive" : "yıkcı",
    "constructive" : "yapıcı",
    "misfortune" : "talihsizlik, terslik",
    "doomed" : "mahkum",
    "monetary" : "parasal",
    "expectancy" : "beklency",
    "transmutation" : "dönüşüm",
    "abode" : "mesken, ikametgah",
    "dominate" : "hakim olmak, hükmetmek",
    "hinder" : "engellemek",
    "deceit" : "aldatma, hile, yalan",
    "deceiving" : "aldatıcı,",
    "conduct" : "yönetmek, idare etmek",
    "admonish" : "uyarmak, ihtar etmek",
    "creed" : "inanç",
    "snap out" : "pat diye söylemek",
    "suffocate" : "boğulmak",
    "supreme" : "yüce",
    "regain" : "yeniden kazanmak",
    "eternal elixir" : "sonsuz iksir",
    "foregoing" : "yukarıdaki, önceki",
    "antidote" : "panzehir",
    "cosmic" : "evrensel",
    "spasmodic" : "aralıklı, süreksiz olan",
    "agency" : "aracı",
    "soil" : "toprak",
    "attracted" : "çekici",
    "demonstrate" : "göstermek",
    "occupy" : "işgal etmek, oturmak, meşgul etmek",
    "deliberately" : "kasten, kasıtlı olarak",
    "seize" : "ele geçirmek",
    "constitute" : "oluşturmak, kurmak",
    "direct" : "yönlendirmek, doğrudan",
    "fertile soil" : "verimli toprak",
    "driving force" : "itici güç",
    "misery" : "sefalet, yoksulluk",
    "prosperity" : "refah, zenginlik",
    "individuality" : "bireysellik",
    "convey" : "iletmek, taşımak",
    "commit" : "işlemek, teslim etmek",
    "stimuli" : "uyaranlar",
    "attune" : "uyum sağlamak, alıştırmak",
    "resolve" : "çözmek, gidermek",
    "unfortunate" : "talihsiz",
    "surmount" : "aşmak, üstesinden gelmek",
    "timidity" : "çekingenlik",
    "arrangement" : "düzenleme, ayarlama",
    "unify" : "birleştirmek",
    "attainment" : "elde etmek, ulaşma",
    "devote" : "adamak",
    "endure" : "dayanmak",
    "engage" : "garanti etmek",
    "induce" : "teşvik etmek",
    "eliminate" : "elemek, gidermek",
    "potion" : "iksir, zehirli içki",
    "hatred" : "kin",
    "envy" : "kıskançlık, imrenmek",
    "cause" : "sebep olmak, neden olmak",
    "self-reliant" : "kendine güvenen",
    "underpinning" : "destekleyici",
    "baffled" : "şaşkın",
    "readily" : "kolayca, çabucak",
    "distress" : "sıkıntı, tehlike",
    "examiner" : "denetçi, müfettiş",
    "disgrace" : "rezalet, utanç",
    "intermingling" : "birbirine karışmak, karıştırmak",
    "mist" : "sis, buğu",
    "intoxicated" : "sarhoş, alkollü",
    "snuff out" : "sonuçlandırmak, bitirmek",
    "prosperity" : "refah, zenginlik",
    "disbelief" : "inançsızlık, güvensizlik",
    "haphazard" : "gelişigüzel",
    "amplify" : "güçlendirmek, yükseltmek",
    "precisely" : "açık olarak, kesinlikle",
    "sail" : "yelken",
    "altitude" : "yükseklik",
    "stagger" : "şaşırtmak",
    "dare" : "cesaret etmek",
    "outclass" : "üstün",
    "emphasize" : "vurgulamak, üzerinde durmak",
    "arouse" : "uyandırmak, canlandırmak",
    "attain" : "ulaşmak, elde etmek",
    "strain" : "tür",
    "sorrow" : "üzüntü",
    "akin" : "benzer",
    "influx" : "akın",
    "demonstrate" : "göstermek, kanıtlamak",
    "astounding" : "şaşırtıcı, hayret verici",
    "wield" : "kullanmak",
    "warfare" : "savaş, harf, savaş hali",
    "coalesce" : "birleşmek",
    "unison" : "uyum",
    "dignity" : "itibar",
    "watchword" : "parola",
    "labor" : "iş gücü",
    "carry out" : "gerçekleştirmek",
    "enlightening" : "aydınlatıcı",
    "dispel" : "gidermek",
    "plainly" : "açıkça",
    "courtesy" : "nezaket",
    "nobility" : "asalet",
    "banquet" : "ziyafet",
    "gratitude" : "minnettarlık",
    "lavish" : "savurgan",
    "hospitality" : "misafirperverlik",
    "bestowed" : "bahşedilen, hediye edilen",
    "stampede" : "izdiham",
    "convention" : "ortak düşünce",
    "bosoms" : "göğüsler",
    "oratory" : "hitabet",
    "bore" : "delik açmak",
    "vaporing" : "buharlaşma",
    "imperial dignity" : "imparatorluk onuru",
    "grace" : "lütuf, zarafet",
    "affair" : "mesele",
    "restrained" : "ölçülü",
    "swept off" : "yerden kesmek",
    "paralyze" : "felç etmek, durdurmak",
    "undermine" : "baltalamak, sarsmak",
    "conceived" : "tasarlanmış",
    "dissolve" : "çözünmek",
    "remark" : "açıklama",
    "stimulate" : "canlandırmak",
    "frenzy" : "çılgınlık",
    "homely" : "sade",
    "epigram" : "iğneli söz",
    "wit" : "zeka",
    "galvanic" : "elektrik çarpmasına benzeyen",
    "orator" : "konuşmacı",
    "recessed" : "gömme",
    "dangling" : "sarkan",
    "full fledged" : "tam teşekküllü",
    "aggrandizement" : "büyütme, çoğaltma",
    "stockjobber" : "borsacı",
    "glued" : "yapıştırılmış",
    "wipe off" : "silmek",
    "wipe out" : "silip yoketmek",
    "divert" : "yönlendirmek, dağıtmak",
    "becloud" : "bulutlandırmak, zorlaştırmak",
    "conceivable" : "makul, akla uygun",
    "assassinate" : "suikast düzenlemek",
    "urget" : "ısrar etmişti",
    "sanctimonious" : "kutsal",
    "foster" : "bakmak",
    "eloquence" : "konuşma sanatı",
    "crackpot" : "çatlak, çılgın",
    "jovial" : "neşeli",
    "forsake" : "terk etmek",
    "picayune" : "önemsiz, beş paralık",
    "dent" : "göçük, çökertmek",
    "eccentric" : "eksantrik, alışılmadık",
    "magnificent" : "muhteşem",
    "amusement" : "eğlence",
    "resentment" : "kızgınlık",
    "retaliation" : "missilleme",
    "rival" : "rakip",
    "lieutenant" : "teğmen",
    "flourishing" : "gelişen",
    "ore" : "cevher",
    "overhead" : "genel gider",
    "administrative" : "yönetim",
    "capturing" : "yakalama",
    "buccaneer" : "korsan",
    "piracy" : "korsanlık",
    "inferred" : "çıkarım",
    "condemn" : "kınamak",
    "shortsightedness" : "miyopluk",
    "hearer" : "dinleyici",
    "expansion" : "genleşme",
    "apostle" : "havari",
    "rosy" : "pembe",
    "anticipation" : "beklenti",
    "indigestion" : "hazımsızlık",
    "assured" : "emin",
    "tread" : "basmak",
    "go-between" : "arabulucu",
    "inconveniently" : "uygunsuz bir şekilde",
    "consummate" : "tamamlamak",
    "endowed" : "donatılmış",
    "copperplate" : "bakır levha",
    "ponder" : "düşünmek, kafa yormak",
    "steadfast" : "sadık",
    "aristocratic" : "aristokrat",
    "scorned" : "küçümsenmiş",
    "concern" : "endişe, kaygı",
    "nominate" : "aday göstermek",
    "conceive" : "tasarlamak",
    "matter" : "konu",
    "undertake" : "üstlenmek",
    "illustration" : "örnekleme",
    "transaction" : "işlem",
    "straighten" : "düzeltmek",
    "persuade" : "ikna etmek",
    "bundled up" : "birlikte paketlenmiş",
    "spirits up" : "morali yükselt",
    "persuasiveness" : "inandırıcılık",
    "capitulated" : "teslim olmuş",
    "intangible" : "soyut",
    "incidental" : "tesadüfi",
    "appraised" : "değerlendirilen",
    "consolidate" : "pekiştirmek",
    "convey" : "iletmek",
    "astounding" : "şaşırtıcı",
    "prospered" : "zengin",
    "common sense" : "sağduyu",
    "accomplish" : "sonuçlandırmak",
    "pioneering" : "öncü",
    "hone" : "geliştirmek",
    "participant" : "katılımcı",
    "annual" : "yıllık",
    "reminisce" : "anmak, anılarını anlatmak",
    "offspring" : "evlat",
    "acknowledge" : "kabullenmek",
    "auto-suggestion" : "kendi kendine telkin",
    "medium" : "araç",
    "recall" : "hatırlamak",
    "permits" : "izin vermek",
    "stimuli" : "uyarıcı",
    "voluntarily" : "gönüllü olarak",
    "perceived" : "algılanan",
    "conscious" : "bilinçli",
    "construe" : "yorumlamak",
    "resemle" : "benzemek",
    "fertile" : "verimli",
    "abundance" : "bolluk",
    "crops" : "mahsul",
    "sown" : "ekilmiş",
    "neglect" : "ihmal etmek",
    "favorable" : "uygun",
    "monetary" : "parasal",
    "endeavoring" : "çabalamak",
    "consciousness" : "bilinç",
    "warrant" : "garanti",
    "appreciable" : "kayda değer",
    "everlasting" : "sonsuz",
    "persistence" : "süreklilik",
    "depend" : "bağlı olmak",
    "retain" : "sürdürmek",
    "favor" : "desteklemek",
    "carry out" : "gerçekleştirmek",
    "fixation" : "sabitleme",
    "legitimate" : "meşru, yasal",
    "consider" : "dikkate almak",
    "awaiting" : "beklemek",
    "hand over" : "devretmek",
    "accumalation" : "birikim",
    "merchandise" : "eşya",
    "fatal" : "ölümcül",
    "preceding" : "önceki",
    "manner" : "tavır, tutum",
    "faulty" : "hatalı",
    "render" : "sunmak",
    "satisfaction" : "memnuniyet",
    "satisfactory" : "tatmin edici",
    "indication" : "gösterge",
    "humility" : "tevazu, alçak gönüllülük",
    "assuming" : "varsaymak",
    "neglect" : "ihmal etmek",
    "blended" : "harmanlanmış",
    "interrupted" : "kesintiye uğramış",
    "accumulate" : "biriktirmek",
    "quantity" : "miktar",
    "quality" : "kalite",
    "portion" : "bölüm, kısım",
    "respresentative" : "temsilci",
    "proportion" : "oran",
    "unfold" : "açılmak",
    "scepticism" : "şüphecilik",
    "characteristic" : "özellik",
    "cooperation" : "işbirliği",
    "hence" : "bundan dolayı, sonra",
    "interim" : "geçici",
    "outlined" : "özetlenen",
    "crystallized" : "belirginleştirmek",
    "earthly" : "dünyevi",
    "thoroughly" : "iyice, tamamen",
    "keystone" : "kilit taşı, temel",
    "arch" : "kemer",
    "inject" : "enjekte etmek",
    "sincere" : "içten",
    "nothing of the sort" : "öyle bir şey yok",
    "aggregate" : "toplam",
    "institution" : "kurum, kuruluş",
    "defy" : "meydan okumak, karşı gelmek",
    "advodate" : "avukat, savunucu",
    "impending" : "yaklaşan, olmak üzere",
    "bidding" : "teklif verme, emir",
    "educe" : "eğitmek, sonuç çıkarmak",
    "draw out" : "çıkarmak, taslağını çizmek",
    "develop from within" : "içeriden gelişmek",
    "editorial" : "başyazı",
    "ignorant" : "cahil",
    "pacifist" : "barışçı",
    "libeling" : "iftira atmak",
    "requisites" : "gereklilikler",
    "salesmanship" : "satıcılık",
    "plead" : "yalvarmak",
    "shameful" : "utanç verici",
    "vile" : "aşağılık, iğrenç",
    "in parting" : "ayrılıkta",
    "draught" : "taslak, tasarı",
    "pleaded justification" : "ileri sürülen gerekçe",
    "justification" : "gerekçe, savunma",
    "pertainin" : "ilgili, ait olmak",
    "plied" : "karşılanmak",
    "leaned over" : "eğilmek",
    "summon" : "çağırmak",
    "devote" : "adamak",
    "unsolicited" : "istenmeyen",
    "subordinate" : "boyun eğdirmek",
    "cater" : "yiyecek ve içecek",
    "clutter up" : "darmadağın etmek",
    "supply" : "sağlamak, tedarik etmek",
    "plain" : "sıradan",
    "acquaintance" : "tanıdık, tanışma",
    "floor" : "şaşırtmak",
    "flop" : "başarısızlık, düşme",
    "inferior" : "kalitesiz",
    "slander" : "iftira",
    "burlesqued" : "şakacı",
    "inferiority" : "aşağılık ",
    "appeal" : "çekici, başvuru",
    "unpardonably" : "affedilmez bir şekilde",
    "gradually" : "gitgide",
    "inclination" : "eğilim",
    "monetary" : "parasal",
    "bridge" : "kapatmak",
    "inferiority complex" : "aşağılık kompleksi",
    "formal" : "resmi, düzgün",
    "reside" : "ikamet",
    "address" : "seslenmek",
    "enthusiastic" : "hevesli, coşkulu",
    "preach" : "vaaz vermek",
    "settle" : "çözülmek",
    "extent" : "kapsam",
    "periodical" : "dönemsel, süreli yayın",
    "contemplate" : "düşünmek",
    "recruiter" : "işveren",
    "chiefly" : "esas olarak",
    "diversify" : "çeşitlendirmek",
    "qualification" : "vasıf, nitelik, yeterlilik",
    "entail" : "gerektirmek",
    "engaged" : "meşgul",
    "desirous" : "arzulu",
    "honing" : "geliştirmek",
    "refer" : "anılmak, bahsetmek",
    "stupendous" : "muazzam",
    "clarification" : "açıklama",
    "spare" : "ayırmak",
    "supplant" : "yerini almak",
    "hearten" : "yüreklendirmek",
    "occupation" : "meslek",
    "adequate" : "yeterli",
    "doomed" : "mahkum",
    "mediocrity" : "sıradanlık",
    "pursuit" : "kovalama",
    "redundant" : "gereksiz",
    "scarce" : "kıt",
    "familiarizing" : "alışma, tanıtmak",
    "nominal" : "cüzi, düşük",
    "fleet" : "filo",
    "adversity" : "sıkıntı",
    "disguise" : "kılık değiştirmek",
    "cultivated" : "kültürlü, görgülü",
    "bountiful" : "cömert, ele açık",
    "exclaim" : "haykırmak, bağırmak",
    "neatly" : "düzgün bir şekilde",
    "merchandising" : "mağazacılık",
    "aggregate" : "toplamak, birleştirmek, toplam",
    "spur" : "teşvik etmek",
    "instantaneous" : "anlık",
    "extensive" : "yaygın",
    "marvelous" : "muhteşem",
    "prophet" : "peygamber",
    "estate" : "arazi, mülk",
    "foretell" : "öngörü, önceden haber vermek",
    "labor" : "emek",
    "procure" : "temin etmek",
    "formation" : "oluşum",
    "sought" : "aranan",
    "sole" : "tek, biricik",
    "hesitate" : "tereddüt etmek",
    "clip off" : "kesilmek, kırpmak",
    "tendency" : "eğilim",
    "rut" : "tekdüzelik, alışılmış şey",
    "cease" : "durdurmak",
    "splendid" : "görkemli",
    "mighty" : "oldukça",
    "unfavorable" : "olumsuz, elverişsiz",
    "scarce" : "kıt",
    "fling" : "kaçmak",
    "motion" : "hareket",
    "dissatisfaction" : "memnuniyetsizlik",
    "mettle" : "cesaret",
    "sink" : "batmak, batırmak",
    "elected" : "seçilmiş",
    "eulogy" : "övgü",
    "compromise" : "anlaşmak, uzlaşmak",
    "substantial" : "önemli, sağlam",
    "emphasize" : "vurgulamak",
    "oratory" : "hitabet, güzel ve etkili konuşma",
    "publicize" : "duyurmak",
    "on one occasion" : "bir vesileyle",
    "cultivating" : "yetiştirme",
    "climax" : "doruğa ulaştırmak, zirveye ulaşmak",
    "draw upon" : "faydalanmak",
    "superior" : "üst, üstün",
    "demonstrate" : "göstermek, kanıtlamak",
    "orator" : "konuşmacı, hatip",
    "revelation" : "vahiy, açığa vurma",
    "realm of religion" : "din alanı",
    "realm of" : "krallığı",
    "envision" : "düşünmek, gözünün önünde getirmek",
    "rival" : "rakip",
    "bring to bear" : "katlanmak",
    "induce" : "teşvik etmek",
    "motive" : "sebep, neden",
    "flattering" : "gurur verici",
    "astonishing" : "şaşırtıcı",
    "divine" : "ilahi, tanrısal",
    "prerogrative" : "ayrıcalık",
    "estate" : "arazi, mülk",
    "willpower" : "irade",
    "reinstate" : "eski durumuna getir",
    "hampered" : "engellemek, engel olmak",
    "cicumscribe" : "sınırlamak, kısıtlamak",
    "regime" : "rejim, sistem",
    "incentive" : "teşvik, özendirici",
    "exalted" : "yüce",
    "cultivate" : "yetiştirmek, geliştirmek",
    "conscience" : "vicdan, inanç",
    "unerring" : "hatasız, şaşmaz",
    "astounding" : "şaşırtıcı",
    "scepticism" : "şüphecilik",
    "deter" : "caydırmak",
    "dreary" : "kasvetli, iç karartıcı",
    "splendid" : "görkemli, muhteşem",
    "soar" : "uçmak, yükselmek",
    "circumvent" : "atlatmak, önlemek",
    "devote" : "adamak",
    "stupendous" : "muazzam",
    "nucleus" : "çekirdek",
    "merit" : "değer",
    "morsel" : "lokma, parça",
    "intricate" : "karmaşık, karışık",
    "piled up" : "yığılı, birikmek",
    "lurking" : "gizlenen",
    "incidentally" : "tesadüfen",
    "alliance" : "ittifak",
    "flair" : "yetenek",
    "supervise" : "denetlemek, gözetmek",
    "typist" : "daktilo, katip",
    "prevailing" : "geçerli",
    "formerly" : "vakti zamanında, eskiden",
    "astonishing" : "şaşırtıcı",
    "stimulus" : "uyarıcı",
    "yield" : "teslim olmak",
    "managerial" : "idari",
    "underpinning" : "destekleyici",
    "capability" : "kabiliyet, kapasite",
    "workshop" : "atölye",
    "fashion" : "şekillendirmek",
    "stimuli" : "uyaranlar, uyarıcı",
    "harnessed" : "koşum takımı, kullanmak",
    "marvelous" : "muhteşem, harika",
    "locomation" : "hareket",
    "apex" : "zirve",
    "commence" : "başlamak",
    "synthetic" : "sentetik",
    "hunch" : "önsezi",
    "tune in to" : "uyum sağlamak",
    "exceedingly" : "fazlasıyla",
    "rapid" : "ani, hızlı",
    "indeed" : "aslında",
    "inaction" : "eylemsizlik",
    "quiescent" : "hareketsiz",
    "ponder on" : "üzerinde düşünmek",
    "nebulous" : "belirsiz",
    "emphemeral" : "geçici",
    "counterpart" : "karşılık",
    "center attention" : "dikkati odaklamak",
    "intangible" : "soyut",
    "tangible" : "somut",
    "evolutionary" : "evrimsel",
    "stupendous" : "muazzam",
    "drafting" : "taslak hazırlamak",
    "determine" : "belirlemek",
    "perceptible" : "algılanabilir, anlaşılır",
    "engaged" : "meşgul",
    "earnestly" : "ciddiyetle",
    "adapt" : "adapte olmak",
    "endeavoring" : "çabalamak",
    "monetary" : "parasal",
    "invincible" : "yenilmez",
    "immutable" : "değişmez",
    "suspend" : "askıya almak",
    "miraculous" : "mucizevi",
    "comprehend" : "anlamak, kavramak",
    "assimilate" : "özümsemek",
    "standing" : "duruş",
    "clarify it" : "açıklığa kavuşturmak",
    "examine" : "incelemek, sınamak",
    "convey" : "iletmek, taşımak",
    "surpass" : "aşmak, geçmek",
    "refining" : "arıtma, inceltme",
    "pouring out" : "dışarı dökülen",
    "prominent" : "öne çıkan, önemli, belirgin",
    "fold up" : "sarmak, dürmek",
    "bras" : "pirinç",
    "thrilling" : "heyecan verici",
    "tale" : "masal",
    "romance" : "romantizm",
    "confess" : "itiraf etmek",
    "supply" : "tedarik, arz",
    "stimulation" : "uyarım, uyarma, teşvik",
    "intoxication" : "sarhoşluk",
    "meritorious" : "değerli",
    "stockyard" : "stok alanı",
    "institution" : "kurum, kuruluş",
    "handicap" : "engel olmak",
    "sets up" : "kurmak",
    "definiteness" : "kesinlik, açıklık",
    "assurance" : "güvence, teminat",
    "sermon" : "vaaz",
    "frankly" : "açıkçası",
    "arise" : "ortaya çıkmak",
    "kneel down" : "diz çökmek",
    "forthcoming" : "gelecek",
    "pulpit" : "kürsü",
    "yield" : "vermek",
    "rear" : "arka, arkadaki",
    "extend" : "uzatmak",
    "reverend" : "rahip",
    "vague" : "belirsiz",
    "vagueness" : "belirsizlik",
    "determined" : "azimli, kararlı",
    "astounding" : "şaşırtıcı, hayret verici",
    "perish" : "yok olmak",
    "impels" : "harekete geçirmek",
    "impartial" : "tarafsız",
    "appeal" : "başvurmak",
    "irreparable" : "onarılamaz",
    "reps" : "temsilciler",
    "flock" : "sürü, yığın",
    "tradeoff" : "değiş tokuş",
    "yield" : "fortune",
    "sorround" : "çevrelemek",
    "accusation" : "suçlama",
    "coax" : "ikna etmek",
    "entice" : "aklını çelmek",
    "gradually" : "gitgide",
    "sweep" : "süpürmek",
    "opposition" : "muhalefet, karşıtlık",
    "frustrated" : "hüsrana uğramış",
    "feasibility" : "uygulanabilirlik",
    "sceptical" : "şüpheci",
    "petiton" : "dilekçe",
    "restraining" : "kısıtlayıcı",
    "enthusiasm" : "heves, heyecan",
    "quash" : "iptal etmek",
    "litigation" : "dava",
    "compromising" : "uzlaşmacı",
    "enthralled" : "büyülenmiş",
    "absence" : "yokluk",
    "innovation" : "yenilik",
    "cultivate" : "yetiştirmek",
    "tender" : "şefkatli, bakıcı",
    "grasp" : "sıkı sıkı tutmak",
    "eliminate" : "elemek, çıkarmak",
    "arise" : "orta çıkmak",
    "ally" : "ittifak kurmak",
    "carrying out" : "gerçekleştirmek, uygulamak",
    "compliance" : "uyma, itaat",
    "belated" : "gecikmiş, geç kalmış",
    "wreck" : "enkaz",
    "neglect" : "ihmal etmek",
    "compensation" : "tazminat",
    "destruction" : "yıkım",
    "adequate" : "yeterli",
    "collectively" : "toplu olarak",
    "harmony" : "uyum",
    "prevail" : "hakim olmak",
    "undertaking" : "girişim",
    "engage" : "meşgul",
    "faultless" : "kusursuz",
    "endeavor" : "çaba, gayret",
    "originate" : "kaynaklanmak, yaratmak",
    "incandescent" : "parlak, göz kamaştırıcı",
    "crown" : "taçlandırmak",
    "railroad" : "demiryolu",
    "reluctant" : "isteksiz, gönülsüz",
    "respective" : "saygılı",
    "enterprise" : "girişim, girişkenlik",
    "envisioned" : "düşünmek, gözünün öne getirmek",
    "incur" : "katlanmak",
    "conviction" : "mahkumiyet",
    "ingenuity" : "yaratıcılık",
    "herd" : "sürü, topluluk",
    "scornfully" : "küçümseyerek",
    "crudely" : "kabaca",
    "contraption" : "mekanizma",
    "belt" : "kuşatmak",
    "backed" : "destekli",
    "piled up" : "yığılı",
    "scoff" : "alay etmek",
    "marching" : "yürüyüş",
    "triumph" : "zafer",
    "covet" : "imrenmek",
    "monetary" : "parasal",
    "inert" : "hareketsiz",
    "compensation" : "tazminat",
    "leisurely" : "yavaş, acelesiz",
    "inevitable" : "kaçınılmaz",
    "fortitude" : "cesaret, dayanıklılık",
    "unswerving" : "şaşmaz, değişmez",
    "outset" : "başlangıç",
    "descendant" : "azalan, torun",
    "squander" : "israf, boşa harcama",
    "timeworn" : "eskimiş, yıpranmış",
    "cling" : "sarılmak",
    "airtight" : "hava geçirmez",
    "justifiable" : "haklı, mazur görülebilir",
    "compile" : "toplamak, sıralamak",
    "obsolete" : "modası geçmiş",
    "assert" : "savunmak",
    "oppose" : "karşı çıkmak",
    "extravagant" : "abartılı, savurgan",
    "what is to be will be" : "olacak olan olacak",
    "entitled" : "hak sahibi",
    "conceive" : "düşünmek",
    "disgrace" : "rezalet, utanç",
    "factor" : "etken",
    "unwavering" : "sarsılmaz",
    "emulate" : "benzemeye çalışmak",
    "command" : "emir vermek",
    "retain" : "sürdürmek",
    "waver" : "tereddüt etmek",
    "rudder" : "dümen (gemi dümeni)",
    "penalty" : "ceza",
    "necessity" : "gereklilik",
    "pleasing" : "hoş",
    "slovenly" : "pasaklı",
    "assume" : "üstlenmek",
    "shift" : "yer değiştirme",
    "incompetent" : "beceriksiz",
    "induce" : "teşvik etmek",
    "consent" : "onay",
    "endure" : "dayanmak",
    "downfall" : "çöküş",
    "be relegated" : "küme düşmek",
    "equitable" : "adil",
    "endure" : "dayanmak, katlanmak",
    "inability" : "yeteneksizlik, yetersizlik",
    "genuine" : "eşsiz, özgün",
    "servant" : "hizmetkar",
    "induce" : "teşvik etmek",
    "render" : "oluşturmak",
    "resentment" : "kızgınlık",
    "content" : "memnun",
    "commendation" : "övgü",
    "intemperance" : "ölçüsüzlük",
    "intemperate" : "aşırı",
    "endurance" : "dayanıklılık",
    "vitality" : "canlılık",
    "indulge" : "şımartmak",
    "dust" : "toz",
    "contempt" : "küçümseme",
    "emphasis" : "vurgu",
    "authority" : "yetki",
    "instill" : "aşılamak",
    "demonstration" : "gösteri",
    "competent" : "yetkili",
    "formality" : "formalite",
    "despondency" : "umutsuzluk",
    "ostentation" : "gösteriş",
    "fertile" : "verimli",
    "decline" : "reddetmek",
    "insestent" : "ısrarcı",
    "racketeer" : "şantajcı",
    "debauched" : "ahlaksız",
    "machiner" : "makineci",
    "burden" : "yük, sorumluluk",
    "reform" : "yenilik",
    "wheels in motion" : "harekete geçmek",
    "dividend" : "kar payı",
    "attitude" : "davranış",
    "birds of a feather flock together" : "tencere yuvarlanmış kapağını bulmuş",
    "regard" : "saygınlık",
    "quasi-public" : "yarı kurumsal",
    "squarely" : "doğrudan",
    "exploitation" : "sömürü, istismar",
    "hardship" : "zorluk",
    "to some extent" : "bir dereceye kadar",
    "conduct" : "yönetmek",
    "relieve" : "rahatlamak",
    "subsidy" : "para yardımı",
    "adequate" : "yeterli, elverişli",
    "passing the buck" : "parayı bşkalarına verme",
    "satisfactory" : "tatmin edici",
    "sufficient" : "yeterli",
    "neatly" : "düzgün şekilde",
    "acquaintance" : "tanıdık",
    "endeavor" : "çaba",
    "peddling" : "seyyar satıcılık",
    "suspect" : "şüphelenmek",
    "consult" : "danışmak",
    "merit" : "değer, esas",
    "prospective" : "muhtemel",
    "prominent" : "öne çıkan",
    "consideration" : "düşünce",
    "probation" : "deneme süresi",
    "trial" : "duruşma",
    "seldom" : "nadiren",
    "incidentally" : "tesadüfen",
    "thoroughly" : "iyice, tamamen",
    "neatness" : "düzgünlük",
    "painstaking" : "özenli",
    "striking" : "dikkat çekici",
    "groom" : "hazırlamak",
    "contrast" : "zıtlık",
    "individuality" : "bireysellik",
    "policy" : "politika",
    "advancement" : "ilerleme, gelişme",
    "deliberate" : "kasten, kasıtlı, planlı",
    "ladder" : "merdiven",
    "stupendous" : "muazzam",
    "underwhelming" : "hayal kırıklığı",
    "marketing of merchandise" : "malların pazarlanması",
    "fellow-employees" : "iş arkadaşları",
    "barter" : "takas, değiş tokuş",
    "courtest" : "nezaket",
    "permanently" : "kalıcı olarak",
    "harmonious" : "uyumlu",
    "conduct" : "davranış",
    "retain" : "sürdürmek",
    "permit" : "izin vermek",
    "conform" : "uymak, uyumlu olmak",
    "substitute" : "yerine geçmek",
    "commodity" : "mal, hammadde",
    "engaged" : "meşgul",
    "competent" : "yetkili",
    "depreciate" : "küçümsemek",
    "sand dune" : "kumul, kum tepesi",
    "persecute" : "acı çektirmek, eziyet etmek",
    "step up" : "artmak, yükselmek",
    "overwhelmingly" : "ezici çoğunlukla",
    "pursuing" : "takip etmek, sürdürmek",
    "unfavorable" : "elverişsiz",
    "hereditary" : "kalıtsal",
    "mediocrity" : "sıradanlık",
    "comparative" : "karşılaştırmalı",
    "comparative ease" : "karşılaştırmalı kolaylık",
    "comparatively" : "nispeten",
    "tackle" : "üstesinden gelmek",
    "outstanding" : "olağanüstü",
    "conducive" : "yararlı",
    "overindulgence" : "aşırı düşkünlük",
    "inadequate" : "yetersiz",
    "twig" : "dal",
    "bent" : "kıvrılmış",
    "tendency" : "eğilim",
    "procrastination" : "erteleme",
    "spoil" : "bozmak",
    "command" : "emretmek",
    "go along" : "devam etmek, ilerlemek",
    "prone" : "yatkın",
    "substitute" : "yerine geçmek",
    "cope" : "başa çıkmak",
    "repel" : "püskürtmek, geri çevirmek",
    "urge" : "dürtü",
    "stimuli" : "uyaranlar, uyarıcı",
    "transmutation" : "dönüşüm",
    "instinct" : "içgüdü",
    "indecision" : "kararsızlık",
    "intimately" : "yakından",
    "bountiful" : "cömert, eli açık",
    "harmonious" : "uyumlu",
    "immunity" : "bağışıklık, dokunulmazlık",
    "indulgence" : "hoşgörü",
    "over-caution" : "aşırı dikkatli",
    "infect" : "bulaştırmak, aşılamak",
    "emulating" : "özenmek",
    "emulate" : "benzemeye çalışmak",
    "superstition" : "batıl inanç",
    "prejudice" : "ön yargı",
    "endeavor" : "çaba",
    "seldom" : "nadiren",
    "indiscriminate" : "ayrım gözetmeyen",
    "spendthrift" : "müsriflik, savurgan",
    "eternally" : "sonsuza kadar",
    "foundation" : "temel",
    "bargaining" : "pazarlık",
    "enthusiasm" : "heves",
    "contagious" : "bulaşıcı",
    "intolerance" : "hoşgörüsüzlük",
    "intemperance" : "ölçüsüzlük",
    "overindulgence" : "aşırı düşkünlük",
    "fatal" : "ölümcül",
    "gradually" : "gitgide",
    "intentional" : "kasıtlı",
    "dishonesty" : "sahtekarlık",
    "substitute" : "yerine geçmek",
    "deed" : "eylem, senet",
    "liberty" : "özgürlük",
    "egotism" : "bencillik",
    "vanity" : "gösteriş",
    "accurately" : "doğru bir şekilde",
    "snap-judgement" : "anlık karar",
    "formidable" : "zorlu, korkunç",
    "lack of capital" : "sermaye eksikliği",
    "beneficial" : "yararlı",
    "admonition" : "öğüt",
    "alibis" : "mazeretler",
    "know thyself" : "kendini tanı",
    "entirely" : "baştan sona",
    "wive" : "eş",
    "folly" : "aptallık",
    "readjustment" : "yeniden ayarlama, düzeltme",
    "inventory" : "stok, envanter",
    "merchandising" : "ticaret yapmak, mağazacılık",
    "sympton" : "belirti",
    "courageously" : "cesurca",
    "disclose" : "ifşa etmek, ortaya çıkarmak",
    "virtue" : "erdem",
    "prompt" : "harekete geçirmek, teşvik etmek",
    "advancement" : "ilerleme, gelişme",
    "deceive" : "aldatmak, kandırmak",
    "harmonious" : "uyumlu",
    "procrastination" : "erteleme, oyalanma",
    "promptly" : "derhal, acilen",
    "occasion" : "fırsat, durum, ortam",
    "subtle" : "hemen göze çarpmayan, zekice",
    "pleasant" : "güzel, keyifli",
    "discrimination" : "ayrımcılık",
    "dissipated" : "dağılmış, harcanmış",
    "tolerant" : "hoşgörülü",
    "intemperate" : "aşırı, ölçüsüz",
    "noteworthy" : "dikkate değer",
    "conservative" : "tutucu, ölçülü",
    "devote" : "ayırmak, adamak",
    "conscience" : "vicdan",
    "courageous" : "cesur, yürekli",
    "libertine" : "çapkın",
    "convey" : "iletmek, taşımak",
    "law-abiding" : "yasalara saygılı",
    "deed" : "senet",
    "curtail" : "kısaltmak, kısmak",
    "molestation" : "sarkıntılık, taciz",
    "constitute" : "oluşturmak, kurmak",
    "shelter" : "barınak",
    "entertainment" : "eğlence",
    "grudge" : "kin, garez",
    "express" : "ifade etmek",
    "ulterior" : "sonraki",
    "aformentioned" : "bahsi geçen",
    "benefactor" : "hayırsever",
    "pioneer" : "öncü",
    "multitudinous" : "çok sayıda",
    "fabric" : "kumaş",
    "withholds" : "stopaj",
    "widespread" : "yaygın",
    "beclouded" : "bulutlu, karartmak, bulutlandırmak",
    "enlightenment" : "aydınlanma",
    "slight" : "hafif, küçük",
    "burden" : "yüklemek",
    "debase" : "değerini düşürmek",
    "confront" : "karşısına çıkmak",
    "endurance" : "dayanıklılık",
    "omit" : "çıkarmak",
    "dairy" : "günlük",
    "hauk" : "çekmek",
    "ingenuity" : "yaratıcılık",
    "enthusiasm" : "heves, coşlu",
    "soapbox orator" : "sokak konuşmacısı",
    "predatory" : "yırtıcı",
    "interest" : "ilgi",
    "condemn" : "kınamak, suçlamak",
    "devote" : "ayırmak",
    "demoagogues" : "halk avcısı",
    "hypochondriac" : "hastalık hastası, evhamlı",
    "poisonous" : "zehirli",
    "partake" : "katılmak, paylaşmak",
    "disturbance" : "rahatsızlık",
    "insanity" : "delilik",
    "raiding" : "baskın",
    "dope-mad" : "uyuşturucu delisi",
    "sway" : "sallanmak",
    "bribe" : "rüşvet",
    "bookkeeping" : "muhasebe",
    "continuation" : "devam etme, sürdürme",
    "ware" : "eşya",
    "irrevocably" : "geri alınamaz bir şekilde",
    "repeal" : "yürürlükten kaldırmak",
    "gruesome" : "korkunç",
    "reach decision" : "karara varmak",
    "disclose" : "ifşa etmek, göstermek",
    "obstinate" : "inatçı",
    "yield" : "kazandırmak",
    "intemperance" : "ölçüsüzlük",
    "detrimental" : "zararlı",
    "humorous" : "komik, gülünç",
    "smattering" : "önemli",
    "self-denying" : "kendini inkar eden",
    "conspicuous" : "göze çarpan",
    "modesty" : "tevazu, alçakgönüllülük",
    "epigram" : "iğneli söz",
    "proclamation" : "bildiri",
    "emancipation" : "özgürleşme",
    "enslave" : "köleleştirmek",
    "compromise" : "uzlaşmak, anlaşmak",
    "momentous" : "çok önemli",
    "intangible" : "soyut",
    "revolution" : "devrim",
    "accessory" : "aksesuar",
    "merit" : "hak etmek, layık olmak",
    "irresistible" : "dayanılmaz",
    "surmount" : "aşmak, üstesinden gelmek",
    "incident" : "olay, kaza",
    "patrolling" : "devriye gezmek",
    "assimilate" : "özümsemek, benimsemek",
    "midst" : "ortasında",
    "hurling" : "fırlatma",
    "swift" : "süratlı, hızlı",
    "epithet" : "lakap",
    "bayonet" : "süngü",
    "arouse" : "uyandırmak, canlandırmak",
    "appoint" : "atamak, tayin etmek",
    "withdrawn" : "geri çekilmiş",
    "withdrawal" : "çekilme",
    "grant" : "kabul etmek",
    "betterment" : "iyileştirme",
    "far-flung" : "uzaklara yayılmış",
    "temple" : "tapınak",
    "apex" : "zirve, tepe",
    "gruntle" : "homurdanma",
    "disgruntle" : "hoşnutsuzluk",
    "imbed" : "gömmek",
    "susceptible" : "duyarlı",
    "resort" : "başvurmak",
    "hatred" : "kin",
    "originate" : "kaynaklanmak, meydana gelmek",
    "loaf of bread" : "somun ekmek",
    "prophecy" : "kehanet",
    "far-fetched" : "zoraki",
    "vain" : "boşuna",
    "superstition" : "batıl inanç",
    "liken" : "benzetmek",
    "yeast" : "maya, köpük",
    "grievance" : "şikayet",
    "conspiracy" : "komplo, anlaşma",
    "embark" : "atılmak, girişmek",
    "consolidate" : "pekiştirmek, sağlamlaştırmak",
    "verboten" : "yasaklanmış",
    "idle" : "boşta",
    "empower" : "güçlendirmek, yetki vermek",
    "dove" : "güvercin",
    "confer" : "görüşmek",
    "cease" : "durdurmak",
    "incur" : "katlanmak, maruz kalmak",
    "treason" : "ihanet",
    "misprision of treason" : "ihanetin yanlış anlaşılması",
    "discretion" : "takdir yetkisi",
    "evasive" : "baştan savma",
    "righteous" : "dürüst",
    "insult" : "hakaret, aşağılama",
    "exasperated" : "bıkkın, kızdırmak",
    "prostitute" : "fahişe",
    "caustic" : "yakıcı, iğneli",
    "forthwith" : "derhal",
    "flagious" : "kötü",
    "condign" : "hoşgörü",
    "slang" : "argo",
    "staunchest" : "en sadık",
    "defiance" : "nispet, saygısızlık",
    "cabinet" : "kabine, dolap",
    "continental" : "kıtasal",
    "declaration" : "beyan, bildirim",
    "province" : "il, vilayet",
    "strained" : "gergin, zoraki",
    "governor" : "vali",
    "solemn" : "ağırbaşlı",
    "consideration" : "düşünce, dikkat almk",
    "ought" : "yapmalı",
    "absolve" : "bağışlamak",
    "allegiance" : "bağlılık",
    "dissolve" : "çözünmek",
    "devastate" : "mahvetmek",
    "reign" : "saltanat",
    "felicity" : "mutluluk",
    "tyranny" : "zorbalık",
    "labor" : "çalışmak, uğraşmak",
    "warrant" : "garanti",
    "firmly" : "kesin olarak, sıkıca",
    "youth" : "gençlik",
    "beneficial" : "yararlı",
    "enrollment" : "kayıt, kaydolma",
    "compelled" : "mecbur",
    "deficiency" : "eksiklik",
    "affix" : "takmak, yapıştırmak",
    "procure" : "temin etmek, sağlamak",
    "whip" : "yenmek",
    "allying" : "müttefik",
    "neglect" : "ihmal etmek",
    "air freight" : "hava taşımacılığı",
    "acquaintance" : "tanıdık",
    "informed" : "bilgili",
    "intimate" : "samimi",
    "freight" : "nakliye",
    "unfeasible" : "imkansız, olanaksız",
    "wield" : "kullanmak",
    "congested" : "sıkışık, kalabalık",
    "counselor" : "danışman, avukat",
    "stimulation" : "uyarım",
    "adopting" : "benimsemek",
    "inconceivable" : "akıl almaz, inanılmaz",
    "sensory" : "duyusal, algısal",
    "feat" : "ustalık, beceri, başarı",
    "stimulant" : "uyarıcı",
    "residing" : "ikamet eden",
    "vigour" : "kuvvet, dinçlik",
    "testimony" : "tanıklık, şahitlik",
    "enormously" : "son derece",
    "dispose" : "elden çıkartmak, düzenlemek",
    "on the contrary" : "aksine",
    "invariably" : "her zaman, sürekli olarak",
    "incidental" : "tesadüfi, olası",
    "cite" : "anmak, alıntı yapmak, bahsetmek",
    "clairvoyance" : "basiret",
    "inconceivably" : "akıl almaz derece",
    "stride" : "adım",
    "form" : "oluşturmak",
    "tollgate" : "gişe, turnike",
    "conslidating" : "toplamak, bir araya getirmek",
    "comprehend" : "anlamak, kavramak",
    "acquainted" : "haberdar olma",
    "liken" : "benzetmek",
    "affinity" : "yakınlık",
    "permeate" : "nüfuz etmek, sızmak",
    "innovative" : "yenilikçi",
    "conviction" : "mahkumiyet, inanç",
    "disaster" : "yıkım, felaket",
    "proxy" : "vekil, vekalet",
    "avail" : "yaramak, fayda, yarar",
    "fiscal" : "mali",
    "sustained" : "sürekli, devamlı",
    "adjusting" : "alışmak",
    "overboard" : "denize",
    "inert" : "hareketsiz, durağan",
    "retention" : "tutulma, alıkoyma",
    "ascertain" : "anlamak, öğrenmek",
    "foregoing" : "yukarıdaki, önceki",
    "assembling" : "birleştirme",
    "comprehensive" : "kapsayıcı, kapsamlı",
    "contemplate" : "düşünmek, tasarlamak",
    "availing" : "faydalanmak",
    "dissipating" : "dağılma, yaymak",
    "discrimination" : "ayrımcılık",
    "intangible" : "soyut, manevi",
    "potentiality" : "potansiyel",
    "biased" : "önyargılı",
    "perpetuation" : "süreklilik",
    "avail" : "fayda, yarar",
    "mediocrity" : "sıradanlık",
    "impelling" : "etkileyici",
    "divest" : "elden çıkarmak, soymak",
    "indulge" : "şımartmak",
    "peculiar" : "özel eşya, tuhaf",
    "counselor" : "danışman, avukat",
    "indulging" : "düşkünlük, şımartmak",
    "composite" : "karışık, bileşik",
    "revival" : "canlanma, uyanış",
    "orgy" : "seks partisi",
    "council" : "konsey, meclis",
    "plentiful" : "bol, çok",
    "cultivation" : "yetiştirme, işleme",
    "imitate" : "taklit etmek, benzetmek",
    "acorn" : "meşe palamudu",
    "oak" : "meşe",
    "sceptical" : "şüpheci, kuşkucu",
    "drawn upon" : "üzerine çizilmiş",
    "appear" : "belli olmak, görünmek",
    "permeate" : "sızmak, geçmek",
    "drown" : "bastırmak",
    "spinless" : "omurgasız",
    "bathing" : "banyo yapmak",
    "autointoxication" : "kendi kendine zehirlenme",
    "weakling" : "zayıflık",
    "carriage" : "taşıma",
    "briskly" : "hızlı bir şekilde",
    "grace" : "merhamet, zarafet",
    "adornment" : "süsleme, süs, dekor",
    "appearance" : "dış görünüş, görünüm",
    "complexion" : "ten, cilt",
}

export default words;
