const words = {    
    "feasible" : "mümkün",
    "capture" : "yakalamak",
    "testify" : "tanıklık",
    "commercial" : "ticari",
    "finance" : "ekonomi",
    "pour" : "dökmek",
    "pack it in" : "stop what one is doing",
    "fortunately" : "neyse ki, iyi ki",
    "cohesion" : "uyum",
    "literacy" : "okuryazarlık",
    "Assets" : "varlık",
    "Acquire" : "elde etmek",
    "Liability" : "yükümlülük",
    "Poured" : "temel atmak",
    "Profound" : "engin",
    "Sink in" : "anlaşılmak",
    "Demeaning" : "aşağılayıcı",
    "Illiterate" : "cahil",
    "Vital" : "hayati",
    "Novice" : "acemi",
    "Naught" : "hiç, boşuna",
    "Mortgage" : "ipotek",
    "Shelter" : "barınak, sığınak",
    "Illustrate" : "gözünde canlandırmak",
    "Accentuate" : "vurgulamak",
    "Malpractice" : "yanlış uygulama",
    "Solely" : "yalnızca, sadece",
    "Aptitude" : "yetenek",
    "Cramped" : "sıkışık",
    "Deducted" : "düşülmek, çıkarılmak",
    "Appliance" : "alet, arac",
    "Creep" : "sürünme",
    "Deduction" : "kesinti",
    "Sigh" : "iç çekmek",
    "Dilemma" : "çıkmaz",
    "Seldom" : "nadiren",
    "Presence" : "mevcudiyet, varlık",
    "Treasure" : "hazine, define, servet",
    "Psychiatrist" : "psikiyatrist",
    "Ostracism" : "dışlanma",
    "Ridicule" : "alay",
    "Outcast" : "dışlanmış",
    "Seek" : "aramak",
    "Mutual fund" : "yatırım fonu",
    "Occasionally" : "ara sıra",
    "Beck" : "emir, they came at his beck",
    "Detest" : "nefret etmek",
    "Preach" : "vaaz vermek, tavsiye vermek",
    "Deviate" : "sapmak",
    "Discourage" : "vazgeçirmek",
    "Latter" : "son, sonuncusu",
    "Excel" : "üstün olmak",
    "Distant" : "mesafeli",
    "Attorney" : "avukat",
    "Corporate" : "şirket",
    "By contrast" : "aksine",
    "Pleasent" : "hoş",
    "Ancillary" : "yan",
    "Utilities" : "araçlar, elektrik, su hizmetleri",
    "Flashy" : "gösterişli",
    "Tend" : "eğilimli olma",
    "Incur" : "meydana gelmek, katlanmak",
    "Put a strain on" : "zorlamak",
    "Lieu" : "yerine",
    "Maintenance" : "bakım",
    "Demonstrate" : "göstermek",
    "Reflect" : "yansıtmak",
    "Balance" : "bakiye",
    "Proportion" : "oran",
    "Debt-ridden" : "borca batmış",
    "Pension" : "emeklilik",
    "Diversify" : "çeşitlendirmek",
    "Tenuous" : "zayıf",
    "Livelihood" : "geçim kaynağı",
    "Genuine" : "eşşiz",
    "Literate" : "okuryazar",
    "Mass" : "kitle",
    "Acquisition" : "edinme",
    "Extent" : "kapsam",
    "Dome" : "kubbe",
    "Labor" : "iş gücü",
    "Turmoil" : "kargaşa",
    "Despite" : "rağmen, aksine, karşın",
    "Detriment" : "aleyhine",
    "Vast majority" : "büyük çoğunluk",
    "Stated" : "belirtilmiş",
    "Laid out" : "ortaya konuldu",
    "Reveal" : "açığa çıkmak",
    "Seemingly" : "görünüşte",
    "Individual" : "bireysel",
    "Welfare" : "refah",
    "Payroll" : "maaş bordrosu",
    "Subsidize" : "mali bakımdan beslemek",
    "Adjourned" : "dağılmak",
    "Graciously" : "nezaketle",
    "Chuckled" : "kıkırdamak",
    "Sight" : "görünüş, bakış açısı",
    "Lost sight of" : "gözden kaybolmak",
    "Intersection" : "kavşak",
    "Globe" : "dünya",
    "Revolve" : "dönmek",
    "State" : "belirtmek",
    "Fiscally" : "mali açıdan",
    "Conservative" : "tutucu",
    "Cling" : "sarılmak",
    "Diligently" : "özenle",
    "Adequately" : "yeterince",
    "Scramble" : "çabalamak",
    "Royalty" : "telif hakkı",
    "Collect" : "toplamak",
    "Fond memories" : "güzel anılar",
    "Diminish" : "azaltmak",
    "Odds" : "ihtimaller",
    "Sophistication" : "karmaşıklık, gelişmişlik",
    "Ultimate" : "nihai, son",
    "Victim" : "mağdur kimse, kurban",
    "Denial" : "inkar",
    "Acknowledge" : "kabullenmek",
    "Accountable" : "sorumlu",
    "Resolve" : "çözmek, gidermek",
    "Indulge" : "şımartmak",
    "Distinction" : "ayrım",
    "Fur" : "Kürk",
    "Impulsively" : "dürtüsel olarak",
    "Burden" : "yük",
    "Hemisphere" : "yarım küre",
    "Subconscious" : "bilinçaltı",
    "Cooperative" : "iş birliği, yardımcı",
    "Obligated" : "yükümlü",
    "Obliged" : "zorunlu",
    "The capital raised" : "toplanan sermaye",
    "Corporation" : "şirket",
    "Comprehensive" : "kapsayıcı",
    "Gracefully" : "Zarifçe",
    "Terminate" : "sonlandırmak",
    "Restrict" : "kısıtlamak",
    "Whereas" : "oysa, halbuki",
    "Appropriate" : "uygun",
    "Concurrency" : "eşzamanlılık",
    "Merit" : "değer",
    "Durability" : "dayanıklılık",
    "Persistence" : "süreklilik",
    "Intercommunication" : "haberleşme, iç iletişim",
    "Resiliency" : "dayanıklılık",
    "Ephemeral" : "geçici",
    "Crook" : "dolandırıcı",
    "Fashioned" : "tanımladı",
    "Levied" : "alınan",
    "Levy" : "vergi",
    "Amendment" : "değişiklik",
    "Constitution" : "anayasa",
    "Wound up" : "sona ermek",
    "Appetite" : "iştah",
    "Sincerely" : "samimi olarak",
    "Strive" : "çabalamak",
    "Prominent" : "öne çıkan",
    "Incentive" : "teşvik",
    "Analogy" : "benzetme",
    "Promote" : "teşvik ",
    "Intuition" : "sezgi",
    "Passage" : "geçiş",
    "İntimidation" : "gözdağı",
    "Virtue" : "erdem",
    "Ladder" : "merdiven",
    "Docile" : "uysal",
    "İntimidating" : "korkutucu",
    "Envision" : "gözünün önüne getirmek",
    "Merely" : "sadece",
    "Occasional" : "ara sıra",
    "Flattering" : "gurur verici",
    "Amassing" : "biriktirme",
    "İnspiring" : "ilham verici",
    "Pounding" : "vurma",
    "Copier" : "fotokopi makinesi",
    "Proverbial" : "meşhur",
    "Accuracy" : "kesinlik",
    "Tumbling" : "yuvarlanma",
    "supply and demand" : "arz ve talep",
    "Litigious" : "davalı",
    "Legitimate" : "meşru, yasal",
    "İnsight" : "iç yüz",
    "Aspire" : "arzulamak",
    "Amplify" : "güçlendirmek",
    "Entity" : "varlık",
    "Sentiment" : "duygu",
    "Allocated" : "tahsis edilmiş",
    "Consultant" : "danışman",
    "to form" : "oluşturmak üzere",
    "Through" : "sayesinde",
    "Comply" : "uymak",
    "İntent" : "amaç, niyet",
    "Proprietor" : "mal sahibi",
    "Scoffe" : "alay",
    "Tremendous" : "muazzam",
    "Daring" : "cesur",
    "İntimately" : "yakından",
    "Detractor" : "küçük düşürücü şey",
    "Urge" : "zorlama, teşvik etmek",
    "Dreading" : "dehşete düşürmek",
    "Precedented" : "benzeri yaşanmış",
    "Prosper" : "gelişmek",
    "Promptly" : "derhal",
    "Accumulate" : "biriktirmek",
    "embrace" : "kucaklamak",
    "embarrassment" : "utanç",
    "maintain" : "sürdürmek",
    "tuned in" : "uyum sağlamak",
    "shrunk" : "daraltmak",
    "poke" : "dürtmek",
    "throughout" : "boyunca",
    "recognize" : "tanımak",
    "hunch" : "önsezi",
    "counting on" : "güvenmek",
    "grasp" : "sıkı sıkı tutmak",
    "enormous" : "kocaman",
    "instantaneously" : "anında",
    "seemingly" : "görünüşte",
    "exponentially" : "üstel olarak",
    "fascinating" : "büyüleyici",
    "unprecedented" : "benzeri görülmemiş",
    "evaluation" : "değerlendirme",
    "doom and gloom" : "kıyamet ve kasvet",
    "significant" : "önemli",
    "prospective" : "muhtemel",
    "feeding frenzy" : "aşırı besleme",
    "sheltered" : "korunuyor",
    "strengthen" : "güçlendirmek",
    "foreclosure" : "haciz",
    "opportunity" : "fırsat",
    "harness" : "kullanmak, yararlanmak",
    "adequate" : "yeterli",
    "seizing" : "yakalamak",
    "awareness" : "farkındalık",
    "regulation" : "düzenleme",
    "precious" : "değerli",
    "wealth" : "varlık, zenginlik, servet",
    "pursuit of wealth" : "zenginlik arayışı",
    "rebound" : "geri tepme",
    "landscape" : "ortam",
    "continually" : "sürekli",
    "hesitate" : "tereddüt etmek",
    "bragging" : "palavra, övünmek",
    "come across" : "karşılaşmak",
    "intention" : "niyet, amaç",
    "pillar" : "sütun",
    "spurt" : "ani çıkış, hamle",
    "job through" : "koşmak",
    "suburb" : "kenar mahalle",
    "ginger" : "zencefil",
    "timber" : "kereste",
    "troubled": "sorunlu",
    "accent" : "vurgu",
    "tenant" : "kiracı",
    "bargain" : "pazarlık",
    "sanitize" : "sterilize etmek",
    "versed" : "usta, tecrübeli",
    "novice" : "acemi",
    "seed" : "tohum",
    "fortunate" : "şanslı",
    "encourage" : "cesaretlendirmek",
    "dues" : "aidat",
    "modest" : "mütevazı",
    "fairly steady" : "oldukça istikrarlı",
    "scar" : "yara izi",
    "assemble" : "birleştirmek",
    "tide" : "gelgit",
    "reside" : "ikamet",
    "rundown" : "bitkin",
    "spooky" : "ürkütücü",
    "wage" : "maaş",
    "tore down" : "yerle bir etmek",
    "raise capital" : "sermayeyi arttırmak",
    "raise" : "artırmak",
    "advisor" : "danışmak",
    "contrasting" : "zıt",
    "overwhelmed" : "bunalmış",
    "emerge" : "ortaya çıkmak, meydana gelmek",
    "brilliance" : "parlaklık",
    "dread" : "korku",
    "dramatic" : "çarpıcı, etkileyici",
    "alter" : "değiştirmek",
    "promissory" : "senet",
    "escrow" : "emanet",
    "ferret out" : "ortaya çıkmak",
    "handing" : "sunmak",
    "curriculum" : "müfredat",
    "willing" : "gönüllü, istekli",
    "self-doubt" : "kendinden şüphe duymak",
    "get ahead" : "öne geçmek",
    "play out" : "rol oynamak",
    "enhance" : "genişletmek",
    "stiffen" : "sertleşti",
    "nod" : "baş sallamak",
    "jot down" : "not almak",
    "deliberately" : "kasten",
    "flare" : "parlama",
    "stoop" : "alçalmak",
    "fumed" : "öfkelenmek",
    "hurry out" : "acele et",
    "humid" : "nemli",
    "amazed" : "şaşırmış",
    "public relation" : "halkla ilişkiler",
    "obnoxious" : "iğrenç, çirkin",
    "antiquated" : "modası geçmiş",
    "controversial" : "tartışmalı",
    "subsidiary" : "yan kuruş",
    "devastated" : "perişan",
    "specalize" : "uzmanlaşmak",
    "thrill" : "heyecan",
    "admit" : "itiraf etmek, kabul etmek",
    "grooming" : "terbiye",
    "construction worker" : "inşaat işçisi",
    "insist" : "ısrar etmek",
    "bewildered" : "şaşkın",
    "freighters" : "yük gemileri",
    "emphasize" : "vurgu",
    "fraternity" : "kardeşlik",
    "rapidly" : "hızlıca",
    "troop" : "birlik",
    "draft-exempt" : "askerliğe elverişsiz, çürük",
    "ashamed" : "utanmış",
    "emerging rations" : "gelişmekte olan ülkeler",
    "manufacture" : "imalat, üretim",
    "means" : "imkan",
    "acronym" : "kısaltma",
    "disastrous" : "felaket",
    "furiously" : "öfkeyle",
    "due" : "vadesi dolmuş",
    "myth" : "efsane",
    "pension" : "emeklilik",
    "lush" : "bereketli",
    "shrug" : "omuz silkmek",
    "hussle" : "güçlük",
    "pinch" : "sıkıntı",
    "fence" : "sınır",
    "unionized" : "sendikalı",
    "specialized" : "uzmanlaşmış",
    "grace" : "zerafet",
    "governor" : "vali",
    "labor unions" : "işçi sendikası",
    "specialist" : "uzman",
    "medical" : "tıbbi",
    "conform" : "uymak",
    "association" : "dernek",
    "clout" : "nüfuz",
    "highly" : "büyük ölçüde",
    "rule of thumb" : "temel kural",
    "sizable" : "oldukça büyük",
    "overspecialization" : "aşırı uzmanlaşma",
    "seek" : "uğraşmak, peşinden koşmak",
    "dividend" : "kar payı, temettü",
    "consider" : "dikkate almak, göz önünde tutmak",
    "management" : "yönetim",
    "spouse" : "eş, hayat arkadaşı",
    "competent" : "yetkili",
    "diminish" : "azaltmak",
    "diminished" : "azalmış",
    "vulnerable" : "hassas",
    "fall back on" : "başvurmak",
    "due to" : "yüzünden, dolayı",
    "pitiful" : "acınası",
    "in addition" : "ek olarak",
    "glaring" : "göze çarpan",
    "perpetuity" : "süreklilik",
    "draw" : "çekmek, almak",
    "related" : "ilgili",
    "ever" : "durmadan, sürekli",
    "archaic" : "eski, modası geçmiş",
    "pro-education" : "eğitim yanlısı",
    "sought" : "aranan",
    "trade" : "ticaret",
    "lay ahead" : "ilerde",
    "commision" : "görev",
    "produce" : "üretmek",
    "warehouse" : "depo",
    "promising job" : "gelecek vaat eden iş",
    "beyond" : "ötesinde ",
    "strike out" : "geçmek",
    "roadblock" : "engel",
    "abundant" : "bol miktarda",
    "arrogance" : "kibir",
    "cynicism" : "alaycılık",
    "dime" : "on sent",
    "pass out" : "bayılmak",
    "phobia" : "fobi",
    "terrified" : "dehşete düşmüş",
    "rhyme" : "kafiye",
    "staggering" : "şaşırtıcı",
    "annualy" : "yıllık",
    "spectacular" : "muhteşem",
    "roach" : "hamam böceği",
    "whimpering" : "sızlanma",
    "duplex" : "dubleks",
    "inspire" : "ilham vermek",
    "mainstay" : "dayanak noktası, dayanak",
    "revoke" : "iptal etmek, geri çekmek",
    "sensational" : "heyecan verici",
    "genuine" : "gerçek",
    "suffice" : "yeterli",
    "intimidating" : "korkutucu",
    "phenomenal" : "olağanüstü",
    "nonetheless" : "her şeye rağmen",
    "nervous" : "gergin",
    "diligence" : "çalışkanlık, çaba",
    "rallying cries" : "toplanma çığlıkları",
    "bury" : "gömmek",
    "determine" : "belirlemek",
    "determined" : "azimli, kararlı",
    "disaster" : "felaket ",
    "somber" : "kasvetli(sıkıntılı), hüzünlü",
    "low-yield bonds" : "düşük getirili tahviller",
    "temper tantrum" : "öfke krizi",
    "spoiled brat" : "şımarık velet",
    "aptitude" : "yetenek",
    "barnyard" : "ahır",
    "impending" : "yaklaşan",
    "stated" : "belirtilmiş",
    "cynic" : "alaycı",
    "paralyze" : "felç etmek, durdurmak",
    "shortcoming" : "eksiklik",
    "immobilize" : "hareketsiz kılmak",
    "knot" : "düğüm",
    "refer" : "bahsetmek, değinmek, başvurmak",
    "fallout shelter" : "serpinti sığınağı",
    "conditioned" : "şartlandırılmış",
    "evaluate" : "değerlendirmek",
    "acknowledge" : "kabullenmek",
    "violence" : "şiddet",
    "order" : "emir",
    "savvy" : "anlayışlı",
    "capital appreciation" : "sermaye takdiri",
    "strictly" : "kesinlikle, tam olarak",
    "resort" : "tatil yeri",
    "mere" : "sadece",
    "remorse" : "vicdan azabı",
    "enforce" : "uygulamak, zorlamak",
    "yield" : "verim, getiri",
    "crippler" : "sakatlayıcı",
    "criticize" : "eleştirmek",
    "expedite" : "hızlandırmak, kolaylaştırmak",
    "deny" : "reddetmek",
    "worry wart" : "endişe yumrusu",
    "substantial" : "önemli",
    "tenacious" : "inatçı",
    "moose" : "geyik",
    "dismayed" : "dehşete düşmek",
    "slips" : "düşmek",
    "irritation" : "sinirlenmek",
    "cure" : "tedavi, çare",
    "yearning" : "hasret",
    "supperssing" : "bastırıcı",
    "trip" : "duygu",
    "stone-broke" : "beş parasız, meteliksiz",
    "spoiled" : "şımartılmış",
    "sacrifice" : "feda etmek, fedakarlıkta bulunmak",
    "spirit" : "ruh",
    "break out" : "çıkmak, patlak vermek",
    "bother" : "zahmet",
    "concerned" : "endişeli, kaygılı",
    "despondency" : "umutsuzluk",
    "attaining" : "elde etmek, ulaşmak",
    "instill" : "aşılamak",
    "damned" : "lanetlenmek",
    "starring" : "başrol",
    "nodde" : "başını sallamak",
    "puny" : "cılız",
    "outright" : "düpedüz",
    "firmly" : "sıkıca",
    "creditor" : "alacaklı",
    "all in all" : "her şeyi düşünerek",
    "weakling" : "zayıf, zayıf kimse",
    "landlord" : "ev sahibi",
    "ignoracne" : "cehalet, cahillik",
    "statement" : "ifade",
    "bluster" : "yaygara, bağıra çağıra konuşmak",
    "spur" : "teşvik etmek",
    "propelled" : "itmek, sevketmek",
    "sensible" : "mantıklı",
    "condo" : "apartman dairesi, konut",
    "overlooked" : "gözden kaçan",
    "spot" : "tespit etmek",
    "cloud" : "bulanıklaştırmak",
    "helplessnes" : "çaresizlik",
    "finances" : "finanse etmek",
    "determination" : "kararlılık",
    "wobbling" : "yalpalama",
    "call upon" : "başvurmak, çağrılmak",
    "absence" : "yokluk",
    "hurdle" : "engel",
    "steward" : "yönetici",
    "burglarized" : "hırsızlığa maruz kalan",
    "immerse" : "kaptırmak",
    "insight" : "içgörü",
    "self-esteem" : "özgüven, özsaygı",
    "clashe" : "çatışmak",
    "accumulated" : "birikmiş",
    "absorb" : "emmek, çekmek, özümsemek",
    "dear" : "sayın",
    "dear friends" : "sevgili arkadaşlar",
    "brag" : "övünmek",
    "dire" : "korkunç",
    "intellectual" : "entelektüel, aydın, zeki",
    "phenomenon" : "olgu, doğal olay, harika",
    "feather" : "tüy",
    "flock" : "akın etmek",
    "slaughter" : "katledilmek",
    "wipe out" : "yok olmak",
    "timid" : "ürkek, çekingen",
    "slant" : "eğimli, meyilli, eğilimli",
    "swell" : "yükselme, kabarma",
    "via" : "aracılığıyla",
    "commodity" : "mal, hammadde",
    "lucrative" : "kazançlı",
    "dough" : "hamur",
    "caveman" : "mağara adamı",
    "blow" : "batırmak",
    "lottery" : "piyango",
    "cruise" : "dolaşmak, gemi gezisi",
    "venture" : "cesarat etmek",
    "delineating" : "sınırlayıcı",
    "fortitude" : "cesaret, dayanıklılık, tahammül",
    "widget" : "araç",
    "enchanced" : "geliştirilmek, yükseltmek, büyütmek",
    "readily" : "kolayca",
    "preach" : "vaaz vermek, tavsiye etmek",
    "allocate" : "paylaştırmak, bölüştürmek",
    "howl" : "uluma",
    "sincerely" : "samimi olarak",
    "wimpy" : "zayıf",
    "doodad" : "karalama",
    "astute" : "zeki, akıllı, kurnaz",
    "dip" : "dalma",
    "fort" : "kale",
    "staunchly" : "sadık bir şekilde",
    "vow" : "yemin",
    "abstinence" : "yoksunluk",
    "age" : "çağ",
    "vacant land" : "boş arazi",
    "settler" : "yerleşimci, göçmen",
    "aback" : "şaşkın",
    "mistaking" : "yanılgı, yanlış anlamak",
    "sophisticated" : "komplike, gelişmiş, çok yünlü",
    "condominium" : "kat mülkiyet",
    "bid" : "teklif etmek, teklif",
    "pump" : "pompa",
    "initial" : "başlangıç, ilk",
    "fluctuation" : "dalgalanma",
    "occasion" : "fırsat",
    "devoted" : "sadık",
    "nasty" : "edepsiz, kötü",
    "voraciously" : "açgözülükle",
    "indicator" : "gösterge",
    "hitch" : "aksaklık",
    "temptation" : "ayartma",
    "resistance" : "direnç",
    "consume" : "tüketmek, harcamak",
    "obey" : "itaat etmek",
    "admire" : "hayran kalmak, takdir etmek",
    "minor" : "küçük",
    "treasure" : "değer vermek",
    "batting" : "vuruş",
    "swing" : "sallanmak",
    "bravado" : "kabadayılık",
    "charitable" : "hayırsever",
    "reciprocity" : "karşılıklılık, karşılıklı olma",
    "firewood" : "yakacak odun",
    "pot-bellied" : "göbekli",
    "stove" : "soba",
    "process" : "süreç",
    "bounty" : "ödül",
    "torrent" : "sel",
    "distinction" : "ayrım",
    "upon" : "üzerine",
    "inspection" : "denetleme, kontrol",
    "retrospect" : "geçmişe bakmak",
    "retrospective" : "geriye dönük",
    "awaken" : "uyanmak, uyandırmak",
    "engagement" : "katılım",
    "unlike" : "aksine",
    "sustain" : "güç vermek, sürdürmek",
    "setback" : "aksilik",
    "urge" : "teşvik etmek",
    "myriad" : "sayısız",
    "power of association" : "çağrışım gücü",
    "go along" : "ilerlemek, devam etmek",
    "prospect" : "olasılık, ihtimal",
    "tolerance" : "hata payı, hoşgörü, tahammül",
    "broker" : "komisyoncu",
    "arose out" : "ortaya çıktı",
    "in essence" : "özünde",
    "fund" : "ödenek",
    "along" : "boyunca",
    "satisfied" : "memnun, tatmin olmuş",
    "assess" : "değer biçmek",
    "insanity" : "delilik",
    "interest" : "faiz",
    "accruing" : "gerçekleşme",
    "moral" : "ders",
    "clause" : "cümle, madde",
    "contingency" : "beklenmedik durum",
    "approval" : "onay, kabul",
    "rediciolous" : "gülünç",
    "identical" : "biberbir aynı",
    "auction" : "açık arttırma",
    "remain" : "sürdürmek, durmak, kalmak",
    "tackle" : "ele almak",
    "abbreviated" : "kısaltılmış",
    "utilized" : "kullanılmış",
    "excessive" : "aşırı",
    "confront" : "karşısına çıkmak",
    "griping" : "üzülmek, yakınmak",
    "intrigue" : "merak uyandırmak",
    "amass" : "yığın, biriktirmek",
    "entertainment" : "eğlence",
    "terror" : "dehşet, korkutan şey",
    "mumbling" : "mırıldanma",
    "await" : "beklemek",
    "fabulous" : "efsanevi, harika, inanılmaz",
    "down payment" : "peşinat",
    "contradict" : "çelişmek",
    "conventional" : "geleneksel",
    "wisdom" : "bilgelik, akıllılık",
    "irreverence" : "saygısızlık",
    "advocate" : "avukat, savunucu",
    "herald" : "haberci, müjdeci",
    "simplifying" : "basitleştirme",
    "resonate" : "yankılanmak",
    "unsettling" : "rahatsız edici",
    "prophetic" : "kehanet gibi",
    "acknowledgement" : "teşekkür",
    "steady" : "istikrarlı",
    "treasured" : "değerli"
}

export default words;